version: "3.8" 
services: 
  web: 
    image: fundamentalsofdocker/ch11-web:2.0 
    build: web 
    ports: 
    - 80:3000 
  db: 
    image: fundamentalsofdocker/ch11-db:2.0  
    build: db 
    volumes: 
    - pets-data:/var/lib/postgresql/data 
volumes: 
  pets-data: